export const ADD_RECOMMENDATION = "ADD_RECOMMENDATION";
export const DELETE_RECOMMENDATION = "DELETE_RECOMMENDATION";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const FETCH_RECOMMENDATIONS_BEGIN = "FETCH_RECOMMENDATIONS_BEGIN";
export const FETCH_RECOMMENDATIONS_SUCCESS = "FETCH_RECOMMENDATIONS_SUCCESS";
export const FETCH_GROUP_RECOMMENDATIONS_SUCCESS = "FETCH_GROUP_RECOMMENDATIONS_SUCCESS";
export const FETCH_RECOMMENDATIONS_FAILURE = "FETCH_RECOMMENDATIONS_FAILURE";
export const SET_NOT_SHOW_ADD = "SET_NOT_SHOW_ADD";
export const SET_SHOW_ADD = "SET_SHOW_ADD";

export const ADD_GROUP = "ADD_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const FETCH_GROUPS_BEGIN = "FETCH_GROUPS_BEGIN";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_ONE_GROUP_SUCCESS = "FETCH_ONE_GROUP_SUCCESS";
export const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";
export const SET_SHOW_COMPONENT = "SET_SHOW_COMPONENT";
export const SET_NOT_SHOW_COMPONENT = "SET_NOT_SHOW_COMPONENT";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const ADD_USER = "ADD_USER";

export const FETCH_CHAT_POSTS_BEGIN = "FETCH_CHAT_POSTS_BEGIN";
export const FETCH_CHAT_POSTS_SUCCESS = "FETCH_CHAT_POSTS_SUCCESS";
export const FETCH_CHAT_POSTS_FAILURE = "FETCH_CHAT_POSTS_FAILURE";
export const ADD_CHAT_POST = "ADD_CHAT_POST";
